import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma's generated client — regenerated by postinstall, gitignored, and
    // the only source of the 19 "unused eslint-disable directive" warnings.
    "src/generated/**",
    // Vendored design prototype, kept for reference and never shipped. Its
    // support.js is bundled third-party code we do not maintain.
    "design_handoff_landing_and_blog_cms/**",
  ]),
]);

export default eslintConfig;
